name: 'artifacts cleanup'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # UTCで5時に実行

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0